config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :galleries do
    resources :images
  end
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    alias_action :create, :read, :update, :destroy, :to => :crud
    cannot :crud, user
    can :crud, Image do |image|
      image.try(:user) == user
    end
    can :crud, Gallery do |gallery|
      gallery.try(:user) == user
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :destroy
  validates_presence_of :user_id
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  belongs_to :gallery
  validates_presence_of :user_id
  validates_presence_of :gallery_id
  has_attached_file :avatar, :styles => {:thumb => "100x100>"}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  def next
    gallery.images.where("id > ?", id).first
  end

  def prev
    gallery.images.where("id < ?", id).last
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :galleries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, notice: "You are not authorized to access this area"
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = current_user.galleries.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    authorize! :read, @gallery
    images = @gallery.images.all.count/3
    @images1 = @gallery.images.limit(images)
    @images2 = @gallery.images.offset(images).limit(images)
    @images3 = @gallery.images.offset(images+images)
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
    authorize! :update, @gallery
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @user = current_user
    @gallery = @user.galleries.build(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    authorize! :update, @gallery
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    authorize! :destroy, @gallery
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    redirect_to galleries_path
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    authorize! :read, @image
    bitly = Shortly::Clients::Bitly
    bitly.apiKey  = ENV['BITLY_API_KEY_ID']
    bitly.login   = ENV['BITLY_LOGIN_USERNAME']
    @url = bitly.shorten(@image.avatar.url(:original)).url
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    redirect_to galleries_path
  end

  # POST /images
  # POST /images.json
  def create
    @gallery = Gallery.find(params[:gallery_id])
    @image = @gallery.images.build(image_params)
    @image.user = current_user

    if @image.save
      render json: { message: "success", fileID: @image.id }, :status => 200
    else
      render json: { error: @image.errors.full_messages.join(',')}, :status => 400
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    authorize! :update, @image
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    authorize! :destroy, @image
    @gallery = Gallery.find(params[:gallery_id])
    @image = @gallery.images.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to gallery_path(@gallery), notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def image_params
    params.require(:image).permit(:avatar)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      redirect_to galleries_path
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/galleries/_form.html.erb
<%= simple_form_for(@gallery) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true, autofocus: true, label: false, placeholder: 'Gallery Name', input_html: {class: 'form-control input-lg'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/galleries/_show.html.erb
<div class="row">
  <div class="col-md-4 col-sm-4">
    <div class="list-group">
      <% @images1.each do |image| %>
          <%= link_to 'Image '+image.id.to_s,gallery_image_path(:gallery_id => @gallery.id, :id => image ), class: 'list-group-item text-center' %>
      <% end %>
    </div>
  </div>
  <div class="col-md-4 col-sm-4">
    <div class="list-group">
      <% @images2.each do |image| %>
          <%= link_to 'Image '+image.id.to_s,gallery_image_path(:gallery_id => @gallery.id, :id => image ), class: 'list-group-item text-center' %>
      <% end %>
    </div>
  </div>
  <div class="col-md-4 col-sm-4">
    <div class="list-group">
      <% @images3.each do |image| %>
          <%= link_to 'Image '+image.id.to_s,gallery_image_path(:gallery_id => @gallery.id, :id => image ), class: 'list-group-item text-center' %>
      <% end %>
    </div>
  </div>
</div>

app/views/galleries/edit.html.erb
<% content_for :title, 'Edit Gallery | ' %>

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h2 class="text-center"><%= link_to '<i class="fa fa-chevron-left"></i> Back'.html_safe, galleries_path, class: 'btn btn-default pull-left' %>Edit Gallery</h2>
      <%= render 'form' %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/galleries/index.html.erb
<% content_for :title, 'Galleries | ' %>

<div class="container">
  <h1 class="text-center">Galleries <%= link_to 'New Gallery', new_gallery_path, class: 'btn btn-primary btn-lg' %></h1>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <table class="table table-striped table-hover">
        <thead>
        <tr>
          <th>Name</th>
          <th class="text-right">Size (MBs)</th>
          <th class="text-right">Images Count</th>
          <th class="text-right"></th>
          <th class="text-right"></th>
        </tr>
        </thead>
        <tbody>
        <% @galleries.each do |gallery| %>
        <% total_size = 0 %>
        <% gallery.images.all.each do |image| %>
            <% total_size += image.avatar_file_size %>
        <% end %>
        <% total_size /= 1000000.0 %>
        <% total_count = gallery.images.all.count %>
            <tr>
              <td><%= link_to gallery.name, gallery %></td>
              <td class="text-right"><%= '%.1f'%total_size %></td>
              <td class="text-right"><%= total_count %></td>
              <td class="text-right"><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
              <td class="text-right"><%= link_to 'Delete', gallery, method: :delete, data: { confirm: 'All Images will also be deleted. Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>


<script>
    <% content_for :scripts do %>
    <% end %>
</script>

app/views/galleries/new.html.erb
<% content_for :title, 'New Gallery | ' %>
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h2 class="text-center"><%= link_to '<i class="fa fa-chevron-left"></i> Back'.html_safe, galleries_path, class: 'btn btn-default pull-left' %>New Gallery</h2>

      <%= render 'form' %>

    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/galleries/show.html.erb
<% content_for :title, @gallery.name+' | ' %>
<div class="container">
  <h2 class="text-center"><%= link_to '<i class="fa fa-chevron-left"></i> Back'.html_safe, galleries_path, class: 'btn btn-default pull-left' %><%= @gallery.name %></h2>
</div>

<div class="container-fluid">
  <%= form_for([@gallery, @gallery.images.build], html: { multipart: true, class: "dropzone"}) do |f| %>
      <div class="fallback">
        <%= f.file_field :avatar %><br>
        <%= f.submit "Upload my Avatar" %>
      </div>
  <% end %>
</div>


<div class="container">
  <div class="show">
    <%= render "show" %>
  </div>
</div>

app/views/galleries/show.js.erb
$(".show").html("<%= escape_javascript(render('show')) %>")

app/views/images/_form.html.erb
<%= simple_form_for([@gallery, @gallery.images.build]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :avatar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.avatar %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/images/show.html.erb
<% content_for :title, 'Image '+ @image.id.to_s + ' | ' %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Image <%= @image.id %><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, gallery_image_path(@image.gallery, @image), method: :delete, class: 'pull-right', data: { confirm: "Are you sure?" } %></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-8">
              <%= link_to '<i class="fa fa-chevron-left"></i> '.html_safe+@image.gallery.name, @image.gallery, class: 'btn btn-default' %>
              <%= link_to @image.avatar.url(:original) do %>
                  <%= image_tag @image.avatar.url(:original), class: 'img-responsive' %>
              <% end %>
            </div>
            <div class="col-md-4">
              <% if @image.next %>
                  <%= link_to 'Next <i class="fa fa-chevron-right"></i>'.html_safe, gallery_image_path(@image.gallery,@image.next), class: 'btn btn-primary pull-right' %>
              <% end %>
              <% if @image.prev %>
                  <%= link_to '<i class="fa fa-chevron-left"></i> Previous'.html_safe, gallery_image_path(@image.gallery,@image.prev), class: 'btn btn-primary pull-left' %>
              <% end %><br><br>
              <div class="well">Share: <%= link_to @url, @url, target: '_blank' %></div>
              Share:
              <div class="text-center">
                <%= link_to 'https://www.facebook.com/dialog/share?
                app_id=145634995501895
                &display=popup
                &href='+@url+'
                &redirect_uri='+@url, target: '_blank' do %>
                    <i class="fa fa-facebook-square fa-4x facebook"></i>
                <% end %>
                <%= link_to 'https://twitter.com/home?status=Check%20this%20pic%3A%20'+@url, target: '_blank' do %>
                    <i class="fa fa-twitter-square fa-4x twitter"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--https://www.facebook.com/dialog/share?-->
<!--app_id=145634995501895-->
<!--&display=popup-->
<!--&href=URL_TO_SHARE-->
<!--&redirect_uri=RETURN_URL-->

<!--'https://www.facebook.com/sharer/sharer.php?u='+@url-->

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
    </div>
    <div class="col-md-2">
      <a href="http://sulman.me/" class="text-muted text-right" target="_blank">
        &copy;2015 Sulman Baig
      </a>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '<i class="fa fa-camera"></i> FotoLib'.html_safe, root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><%= link_to '<i class="fa fa-camera-retro"></i> Galleries'.html_safe, galleries_path %></li>
            <li><%= link_to '<i class="fa fa-cog"></i> Settings'.html_safe, edit_user_registration_path %></li>
            <li><%= link_to '<i class="fa fa-sign-out"></i> Log Out'.html_safe, destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to '<i class="fa fa-info-circle"></i> About'.html_safe, about_path %></li>
            <li><%= link_to '<i class="fa fa-sign-in"></i> Log In'.html_safe, new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= yield :title %>FotoLib</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/header' %>
</header>
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <% flash.each do |type, message| %>
          <div class="alert alert-info fade-in">
            <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>
<section>
  <%= yield %>
</section>

<footer class="footer">
  <%= render 'layouts/footer' %>
</footer>

<script type="text/javascript">
    $(document).ready(function(){
        <%= yield :scripts %>
    });
</script>
</body>
</html>

app/views/pages/about.html.erb
<% content_for :title, 'About | ' %>

<div class="jumbotron">
  <div class="container">
    <p>This app helps you to save the images only and make them private until you share them with others. Its free of cost. Unlimited storage.
      This app is made by <a href="http://sulman.me/" target="_blank">Mirza Sulman Baig</a></p>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for :title, 'Home | ' %>

<div class="jumbotron">
  <div class="container">
    <h1><i class="fa fa-camera"></i> FotoLib</h1>
    <p>Private photo saving, managing and sharing app.</p>
    <p>
      <%= link_to '<i class="fa fa-sign-in"></i> Log In'.html_safe, new_user_session_path, class:'btn btn-primary btn-lg' %>
      <%= link_to '<i class="fa fa-sign-in"></i> Sign Up'.html_safe, new_user_registration_path, class:'btn btn-default btn-lg' %>
    </p>
  </div>
</div>

app/views/pages/temp.html.erb
<% content_for :title, 'Galleries | ' %>




<script>
    <% content_for :scripts do %>
    <% end %>
</script>